import Testing
import Foundation
import simd
@testable import FoldCore

/// The Python writer in `Tools/pftraj.py` and the Swift reader must agree byte for byte.
/// Every bundled trajectory is produced by the Python side and read by the Swift side, so a
/// disagreement here would show up as a silently mangled protein rather than an error.
///
/// The fixture is regenerated by `Tools/make_fixture.py`; the values in it are chosen to be
/// exactly representable in float32 so these assertions can be exact.
@Suite("Cross-language .pftraj compatibility")
struct CrossLanguageCodecTests {

    static func fixtureURL() throws -> URL {
        try #require(Bundle.module.url(forResource: "Fixtures/python-written",
                                       withExtension: "pftraj"),
                     "the Python-written fixture is missing from the test bundle")
    }

    @Test("a file written by Tools/pftraj.py decodes in Swift")
    func decodesPythonFile() throws {
        let bundle = try TrajectoryBundleCodec.read(contentsOf: Self.fixtureURL())

        #expect(bundle.metadata.name == "Cross-language fixture")
        #expect(bundle.metadata.sequence == "MKVFGRCEL")
        #expect(bundle.metadata.provenance == .testFixture)
        #expect(bundle.metadata.accession == "P00698")
        #expect(bundle.metadata.organism == "Gallus gallus")
        #expect(bundle.metadata.referencePDBID == "1UBQ")
        #expect(bundle.metadata.blocksPerReadout == 4)
        #expect(bundle.metadata.recycles == 2)
        #expect(bundle.metadata.residueCount == 9)

        #expect(bundle.readouts.count == 4)
        #expect(bundle.isConsistent)
    }

    @Test("coordinates and pLDDT match the values Python wrote, exactly")
    func coordinatesMatch() throws {
        let bundle = try TrajectoryBundleCodec.read(contentsOf: Self.fixtureURL())

        for (f, readout) in bundle.readouts.enumerated() {
            #expect(readout.recycle == f / 2)
            #expect(readout.blockIndex == f * 4)
            for k in 0..<9 {
                let base = SIMD3<Float>(Float(k) * 3.75 - 11.25, Float(f) * -0.5, Float(k) * 0.25)
                let r = try #require(readout.backbone)[k]
                #expect(r.ca == base)
                #expect(r.n == base + SIMD3<Float>(-0.5, 0.125, -0.625))
                #expect(r.c == base + SIMD3<Float>(0.5, -0.125, 0.625))
                #expect(r.o == base + SIMD3<Float>(0.875, 0.5, 0.75))
                #expect(readout.confidence[k] == Float(k) * 1.5 + Float(f) * 3.25)
            }
        }
    }

    @Test("residues resolve through the sequence")
    func residues() throws {
        let bundle = try TrajectoryBundleCodec.read(contentsOf: Self.fixtureURL())
        #expect(bundle.residues == [.methionine, .lysine, .valine, .phenylalanine,
                                    .glycine, .arginine, .cysteine, .glutamicAcid, .leucine])
    }

    /// A test fixture must never reach an app bundle. The Phase 0 gate checks the shipped
    /// directory; this checks the invariant at the type level.
    @Test("test-fixture provenance is distinguishable from real inference")
    func provenanceIsHonest() throws {
        let bundle = try TrajectoryBundleCodec.read(contentsOf: Self.fixtureURL())
        #expect(bundle.metadata.provenance != .esmFoldReadout)
        #expect(bundle.metadata.provenance != .coreMLTrunkStep)
    }
}
