import Foundation
import simd
import FoldCore

/// CA-only secondary structure assignment by a small trained classifier.
///
/// P-SEA reaches 79.4% agreement with DSSP and cannot reach PLAN.md's 85% gate, because its
/// five-residue seeding cannot detect a three-residue 3-10 helix at all. This replaces it as
/// the default. `PSEA` remains in the package as a baseline and a regression guard.
///
/// The model is a 5,699-parameter multilayer perceptron over the same CA-only geometry P-SEA
/// uses, plus contact-shell counts that let it see beta pairing. Trained on 118 PDB chains
/// with mkdssp labels; **the ten evaluation structures were excluded from the dataset
/// entirely**, so the gate measures generalisation rather than recall.
///
/// Viterbi smoothing was trained and measured, then deliberately **not** used: it cost
/// accuracy (91.6% to 89.9%) and over-smoothed segmentation badly. Details in the model file
/// and in METRICS.md. Temporal stability across frames is `SSHysteresis`, a separate concern.
public struct LearnedSSE: Sendable {

    struct Layer: Decodable, Sendable {
        let weight: [[Float]]     // [out][in]
        let bias: [Float]
        let relu: Bool
    }

    struct Model: Decodable, Sendable {
        let featureCount: Int
        let window: Int
        let shells: [[Float]]
        let minSeparation: Int
        let layers: [Layer]
        let validationAccuracy: Double
        let trainingChains: Int
    }

    let model: Model

    /// The bundled classifier. `nil` only if the resource is missing or malformed, in which
    /// case the caller should fall back to `PSEA` rather than fail: an assignment is a
    /// display detail, not a reason to lose a fold.
    public static let bundled: LearnedSSE? = {
        guard let url = Bundle.module.url(forResource: "sse_classifier", withExtension: "json"),
              let data = try? Data(contentsOf: url),
              let model = try? JSONDecoder().decode(Model.self, from: data)
        else { return nil }
        return LearnedSSE(model: model)
    }()

    public var validationAccuracy: Double { model.validationAccuracy }
    public var parameterCount: Int {
        model.layers.reduce(0) { $0 + $1.weight.count * ($1.weight.first?.count ?? 0) + $1.bias.count }
    }

    // MARK: - Features

    /// Feature vector per residue. **Must match `Tools/sse_features.py` exactly**; a parity
    /// test asserts it against a fixture generated by the Python side.
    public func features(caPositions ca: [SIMD3<Float>]) -> [[Float]] {
        let n = ca.count
        guard n > 0 else { return [] }

        var d2 = [Float](repeating: .nan, count: n)
        var d3 = [Float](repeating: .nan, count: n)
        var d4 = [Float](repeating: .nan, count: n)
        var theta = [Float](repeating: .nan, count: n)
        var alpha = [Float](repeating: .nan, count: n)
        for i in 1..<max(n - 1, 1) {
            d2[i] = simd_distance(ca[i - 1], ca[i + 1])
            theta[i] = PSEA.angle(ca[i - 1], ca[i], ca[i + 1])
        }
        if n >= 3 {
            for i in 1..<max(n - 2, 1) {
                d3[i] = simd_distance(ca[i - 1], ca[i + 2])
                alpha[i] = PSEA.dihedral(ca[i - 1], ca[i], ca[i + 1], ca[i + 2])
            }
        }
        if n >= 4 {
            for i in 1..<max(n - 3, 1) { d4[i] = simd_distance(ca[i - 1], ca[i + 3]) }
        }

        // Contact-shell counts: how a strand is told apart from an extended coil.
        var contacts = [[Float]](repeating: [Float](repeating: 0, count: model.shells.count),
                                 count: n)
        for i in 0..<n {
            for j in 0..<n where abs(i - j) >= model.minSeparation {
                let d = simd_distance(ca[i], ca[j])
                for (k, shell) in model.shells.enumerated()
                where d >= shell[0] && d < shell[1] {
                    contacts[i][k] += 1
                }
            }
        }

        let w = model.window
        var out: [[Float]] = []
        out.reserveCapacity(n)
        for i in 0..<n {
            var row: [Float] = []
            row.reserveCapacity(model.featureCount)
            for offset in (-w)...w {
                let j = i + offset
                if j >= 0, j < n, d3[j].isFinite {
                    row.append((d2[j].isFinite ? d2[j] : 0) / 10)
                    row.append(d3[j] / 10)
                    row.append((d4[j].isFinite ? d4[j] : 0) / 10)
                    row.append((theta[j].isFinite ? theta[j] : 0) / 180)
                    let radians = alpha[j] * .pi / 180
                    row.append(alpha[j].isFinite ? cos(radians) : 0)
                    row.append(alpha[j].isFinite ? sin(radians) : 0)
                    row.append(1)
                } else {
                    row.append(contentsOf: [Float](repeating: 0, count: 6))
                    row.append(0)
                }
            }
            for c in contacts[i] { row.append(c / 10) }
            row.append(Float(min(i, n - 1 - i)) / 10)
            out.append(row)
        }
        return out
    }

    // MARK: - Inference

    /// Class logits per residue, in the order helix, sheet, coil.
    public func logits(features rows: [[Float]]) -> [[Float]] {
        rows.map { row in
            var activation = row
            for layer in model.layers {
                var next = layer.bias
                for o in 0..<layer.weight.count {
                    let weights = layer.weight[o]
                    var sum: Float = 0
                    for i in 0..<weights.count { sum += weights[i] * activation[i] }
                    next[o] += sum
                }
                if layer.relu { for i in next.indices { next[i] = max(0, next[i]) } }
                activation = next
            }
            return activation
        }
    }

    /// Assign secondary structure to a CA trace.
    ///
    /// Confidence is the softmax probability of the chosen class, so it is a real posterior
    /// rather than a heuristic, and drives the renderer's morph directly.
    public func assign(caPositions ca: [SIMD3<Float>]) -> [SSAssignment] {
        guard ca.count >= 5 else {
            return [SSAssignment](repeating: .unassigned, count: ca.count)
        }
        return logits(features: features(caPositions: ca)).map { row in
            let highest = row.max() ?? 0
            let exponentials = row.map { exp($0 - highest) }
            let total = exponentials.reduce(0, +)
            var bestIndex = 0
            for i in row.indices where row[i] > row[bestIndex] { bestIndex = i }
            let probability = total > 0 ? exponentials[bestIndex] / total : 0
            let structure: SecondaryStructure = switch bestIndex {
            case 0: .helix
            case 1: .sheet
            default: .coil
            }
            if structure == .coil { return SSAssignment(structure: .coil, confidence: 0) }
            return SSAssignment(structure: structure, confidence: probability)
        }
    }
}

/// Which assigner the engine uses. The learned model is the default; P-SEA remains available
/// and is what runs if the bundled weights cannot be loaded.
public enum SecondaryStructureAssigner: Sendable {
    case learned
    case pSEA

    public func assign(caPositions ca: [SIMD3<Float>]) -> [SSAssignment] {
        switch self {
        case .learned:
            if let model = LearnedSSE.bundled { return model.assign(caPositions: ca) }
            return PSEA.assign(caPositions: ca)
        case .pSEA:
            return PSEA.assign(caPositions: ca)
        }
    }
}
